openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0
tags:
  - name: Answer
    description: API for managing answers
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /api/answer:
    post:
      tags: [ Answer ]
      summary: Create a new answer
      description: Create a new answer with optional file uploads
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                text:
                  type: string
                questionId:
                  type: number
                files:
                  type: array
                  items:
                    type: string
                    format: binary
              required:
                - text
                - questionId
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                userId:
                  type: number
                questionId:
                  type: number
              required:
                - text
                - questionId
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Answer created successfully.

  /api/answer/{id}:
    delete:
      tags: [ Answer ]
      summary: Delete an answer by ID
      description: Deletes the answer with the specified ID. Requires ADMIN role.
      parameters:
        - in: path
          name: id
          required: true
          description: Numeric ID of the answer to delete.
          schema:
            type: integer
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Answer deleted successfully.
        '401':
          description: Unauthorized. User is not authenticated or does not have ADMIN role.
        '404':
          description: Answer not found.
        '500':
          description: Internal server error.
