openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0
tags:
  - name: Category
    description: Category management
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /api/category:
    post:
      summary: Create a new category
      tags: [ Category ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: A category creation

    get:
      summary: Get all categories
      tags: [ Category ]
      responses:
        '200':
          description: A list of categories

  /api/category/{id}:
    delete:
      summary: Delete a category by ID
      tags: [ Category ]
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            minimum: 1
          required: true
          description: ID of the category to delete
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: A category deletion

    patch:
      summary: Update a category by ID
      tags: [ Category ]
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            minimum: 1
          required: true
          description: ID of the category to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: A category update
