openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0
tags:
  - name: Question
    description: Questions API
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /api/question:
    post:
      summary: Create a new question
      tags: [ Question ]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                text:
                  type: string
                categoryId:
                  type: integer
                files:
                  type: array
                  items:
                    type: string
                    format: binary
              required:
                - text
                - categoryId
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: A question object
    get:
      summary: Get a list of questions
      tags: [ Question ]
      parameters:
        - in: query
          name: categoryId
          schema:
            type: integer
          description: ID of the category to filter by
        - in: query
          name: isAnswered
          schema:
            type: boolean
          description: Whether to filter by answered questions
        - in: query
          name: limit
          schema:
            type: integer
          description: Maximum number of questions to return
        - in: query
          name: page
          schema:
            type: integer
          description: Page number to return
      responses:
        '200':
          description: An array of question objects

  /api/question/{id}:
    get:
      summary: Get a question by ID
      tags: [ Question ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the question to retrieve
      responses:
        '200':
          description: A question object

    delete:
      summary: Delete a question by ID
      tags: [ Question ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the question to delete
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Deletion successful message
          content:
            application/json:
              schema:
                type: string
