openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0
tags:
  - name: Vote
    description: API for managing votes
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /api/vote:
    post:
      tags: [ Vote ]
      summary: Create a new vote
      description: Create a new comment for question or answer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                vote:
                  type: number
                questionId:
                  type: number
                answerId:
                  type: number
              required:
                - vote
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Vote created successfully.
        '400':
          description: Bad Request. Invalid input data.
        '401':
          description: Unauthorized. User is not authenticated.
        '500':
          description: Internal server error.

    delete:
      tags: [ Vote ]
      summary: Delete a vote by userId, questionId, answerId
      description: Deletes the vote. Requires authentication.
      parameters:
        - in: path
          name: answerId
          required: false
          description: Numeric ID of the answer.
          schema:
            type: integer
        - in: path
          name: questionId
          required: false
          description: Numeric ID of the question.
          schema:
            type: integer
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Vote deleted successfully.
        '401':
          description: Unauthorized. User is not authenticated or does not have ADMIN role.
        '404':
          description: Vote not found.
        '500':
          description: Internal server error.

  /api/vote/{answerId}:
    get:
      tags: [ Vote ]
      summary: Get all votes
      description: Get all user's votes for specified question
      parameters:
        - in: path
          name: questionId
          required: true
          schema:
            type: integer
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: Votes fetched successfully.
        '400':
          description: Bad Request. Invalid input data.
        '401':
          description: Unauthorized. User is not authenticated.
        '500':
          description: Internal server error.



