export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const QUESTION_ROUTE = '/question'
export const QUESTIONS_ROUTE = '/questions'
export const PROFILE_ROUTE = '/profile'
export const MAIN_ROUTE = '/'
